services:
  postgres-db:
    image: postgres:14-alpine
    hostname: 0.0.0.0
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  mongo-db:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - ~/mongo:/data/db

  redis-db:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - ~/redis:/data
