services:
  postgres-db:
    # image: postgres:14-alpine
    image: postgres
    hostname: 0.0.0.0
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo_db

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres-db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

  mongo-db:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - ./mongo-volume:/data/db

  redis-db:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - ./redis-volume:/data
