version: '3.8'

services:
  # react-vite:
  #   build:
  #     context: ./react-vite
  #   ports:
  #     - 3341:3000
  #   volumes:
  #     - ./react-vite:/app # ./react-vite is host directory, /app is container directory
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true # watch file changes on host directory

  # react-nextjs:
  #   build:
  #     context: ./react-nextjs
  #   ports:
  #     - 3343:3000
  #   volumes:
  #     - ./react-nextjs:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  node-express:
    build:
      context: ./node-express
    ports:
      - 3342:3000
    volumes:
      - ./node-express:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - backend
  # redis:
  #   image: redis
  #   container_name: redis-image
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - ./data:/data

  # backend-mongo:
  #   build:
  #     context: ./backend-mongo
  #   ports:
  #     - 3344:3000
  #   volumes:
  #     - ./backend-mongo:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
