# version: '3.7'

services:
  node-express:
    profiles: ['ServiceDisabled']
    build:
      context: ./node-express
    ports:
      - 3345:3000
    volumes:
      - ./node-express:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    deploy:
      resources:
        limits:
          memory: 0.5G
    # depends_on:
    #   - redis-db
  postgres-db:
    profiles: ['ServiceDisabled']
    image: postgres:14-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis-db:
    profiles: ['ServiceDisabled']
    image: redis/redis-stack-server:latest
    restart: always
    # command: --port 6379
    ports:
      - '6379:6379'
    expose:
      - '6379'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ~/redis:/data

  react-vite:
    profiles: ['ServiceDisabled']
    build:
      context: ./react-vite
    ports:
      - 3341:3000
    volumes:
      - ./react-vite:/app # ./react-vite is host directory, /app is container directory
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # watch file changes on host directory

  react-nextjs:
    profiles: ['ServiceDisabled']
    build:
      context: ./react-nextjs
    ports:
      - 3342:3000
    volumes:
      - ./react-nextjs:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  backend-network:
    external: true
