version: '3.8'

services:
  # node-express:
  #   build:
  #     context: ./node-express
  #   ports:
  #     - 3345:3000
  #   volumes:
  #     - ./node-express:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   # depends_on:
  #   #   - backend
  # postgres-db:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis-db:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ~/redis:/data
  # redis-db:
  #   # image: redis:latest
  #   # image: redis:7.4.0-alpine
  #   image: redis:6.2-alpine
  #   # restart: always
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis:/data
  # volumes:
  #   - /path/to/local/d–∞ta:/root/redis
  #   - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
  # environment:
  #   - REDIS_PASSWORD=my-password
  #   - REDIS_PORT=6379
  #   - REDIS_DATABASES=16

  # services:
  #   postgres:
  #     image: postgres:14-alpine
  #     ports:
  #       - 5432:5432
  #     volumes:
  #       - ~/apps/postgres:/var/lib/postgresql/data
  #     environment:
  #       - POSTGRES_PASSWORD=S3cret
  #       - POSTGRES_USER=citizix_user
  #       - POSTGRES_DB=citizix_db
# docker run --name es01  -p 9200:9200 docker.elastic.co/elasticsearch/elasticsearch:8.14.3

# react-vite:
#   build:
#     context: ./react-vite
#   ports:
#     - 3341:3000
#   volumes:
#     - ./react-vite:/app # ./react-vite is host directory, /app is container directory
#     - /app/node_modules
#   environment:
#     - CHOKIDAR_USEPOLLING=true # watch file changes on host directory

# react-nextjs:
#   build:
#     context: ./react-nextjs
#   ports:
#     - 3342:3000
#   volumes:
#     - ./react-nextjs:/app
#     - /app/node_modules
#   environment:
#     - CHOKIDAR_USEPOLLING=true
