services:
  postgres-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis-db:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - 6379
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ~/redis:/data
