version: '3.8'

services:
  frontend-vite:
    build:
      context: ./vite-project
    ports:
      - 3341:3000
    volumes:
      - ./vite-project:/app # ./vite-react is host directory, /app is container directory
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # watch file changes on host directory
    # depends_on:
    #   - backend

  backend-express:
    build:
      context: ./express-project
    ports:
      - 3342:3000
    volumes:
      - ./express-project:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend-nextjs:
    build:
      context: ./nextjs-project
    ports:
      - 3343:3000
    volumes:
      - ./nextjs-project:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend-mongo:
    build:
      context: ./backend-mongo
    ports:
      - 3344:3000
    volumes:
      - ./backend-mongo:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
