version: '3.8'

services:
  node-express:
    build:
      context: ./node-express
    ports:
      - 3345:3000
    volumes:
      - ./node-express:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - backend

  # react-vite:
  #   build:
  #     context: ./react-vite
  #   ports:
  #     - 3341:3000
  #   volumes:
  #     - ./react-vite:/app # ./react-vite is host directory, /app is container directory
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true # watch file changes on host directory

  # react-nextjs:
  #   build:
  #     context: ./react-nextjs
  #   ports:
  #     - 3342:3000
  #   volumes:
  #     - ./react-nextjs:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
