version: '3.8'

services:
  frontend:
    build:
      context: ./vite-react
    ports:
      - 5173:5173
    volumes:
      - ./vite-react:/app # ./vite-react is host directory, /app is container directory
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # watch file changes on host directory
    # depends_on:
    #   - backend

  backend:
    build:
      context: ./express-project
    ports:
      - 3000:3000
    volumes:
      - ./express-project:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend2:
    build:
      context: ./create-react-app
    ports:
      - 3001:3000
    volumes:
      - ./create-react-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend2:
    build:
      context: ./backend-mongo
    ports:
      - 3003:3000
    volumes:
      - ./backend-mongo:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
