version: '3.8'

services:
  react-vite:
    build:
      context: ./react-vite
    ports:
      - 3341:3000
    volumes:
      - ./react-vite:/app # ./vite-react is host directory, /app is container directory
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # watch file changes on host directory
    # depends_on:
    #   - backend

  node-express:
    build:
      context: ./node-express
    ports:
      - 3342:3000
    volumes:
      - ./node-express:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  nextjs-react:
    build:
      context: ./nextjs-react
    ports:
      - 3343:3000
    volumes:
      - ./nextjs-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # backend-mongo:
  #   build:
  #     context: ./backend-mongo
  #   ports:
  #     - 3344:3000
  #   volumes:
  #     - ./backend-mongo:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
