services:
  node-express:
    # profiles: [service-disabled]

  react-vite:
    profiles: [service-disabled]

  react-nextjs:
    profiles: [service-disabled]

  postgres-db:
    profiles: [service-disabled]

  mongo-db:
    # profiles: [service-disabled]

  redis-db:
    profiles: [service-disabled]
